[tool.poetry]
name = "optisense-glazunya"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
uvicorn = "^0.32.1"
pydantic-settings = "^2.6.1"
envparse = "^0.2.0"
gunicorn = "^23.0.0"
taskiq = "^0.11.17"
taskiq-redis = "^1.0.8"
taskiq-fastapi = "^0.3.5"
aiohttp = "^3.12.7"
numpy = "^2.2.6"
opencv-python = "^4.11.0.86"
openvino = "^2025.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
